// Code generated by "gends"; DO NOT EDIT.

package set // import "kkn.fi/set"

// Complex128Set implements a set data structure that holds complex128s.
type Complex128Set struct {
	m map[complex128]struct{}
}

// NewComplex128 creates a set of complex128s initialized with given values.
func NewComplex128(values ...complex128) *Complex128Set {
	s := &Complex128Set{}
	s.m = make(map[complex128]struct{})
	s.Add(values...)
	return s
}

// Add adds given values to the set.
func (s *Complex128Set) Add(values ...complex128) {
	if len(values) == 0 {
		return
	}
	for _, value := range values {
		s.m[value] = valueExists
	}
}

// Contains returns true if set holds all values and false otherwise.
func (s Complex128Set) Contains(values ...complex128) bool {
	if len(values) == 0 {
		return false
	}
	for _, value := range values {
		if _, has := s.m[value]; !has {
			return false
		}
	}
	return true
}

// Remove removes given values from the set.
func (s *Complex128Set) Remove(values ...complex128) {
	if len(values) == 0 {
		return
	}
	for _, value := range values {
		delete(s.m, value)
	}
}

// Clear removes all values from the set.
func (s *Complex128Set) Clear() {
	s.m = make(map[complex128]struct{})
}

// Visit iterates through the set and visits all values with function f.
// Iteration will stop if function f returns false.
// Visit will return false when set is visited partially.
func (s Complex128Set) Visit(f func(value complex128) bool) bool {
	for v := range s.m {
		if !f(v) {
			return false
		}
	}
	return true
}

// Copy returns a copy of the set.
func (s Complex128Set) Copy() *Complex128Set {
	return NewComplex128(s.Slice()...)
}

// Equals returns true if both sets are equal, but false otherwise.
func (s Complex128Set) Equals(other *Complex128Set) bool {
	if s.Len() != other.Len() {
		return false
	}
	e := true
	other.Visit(func(value complex128) bool {
		_, e = s.m[value]
		return e
	})
	return e
}

// IsSubset returns true if given set is a subset of s.
func (s Complex128Set) IsSubset(other *Complex128Set) bool {
	result := true
	other.Visit(func(value complex128) bool {
		_, result = s.m[value]
		return result
	})
	return result
}

// IsSuperset returns true if given set is a superset of s.
func (s Complex128Set) IsSuperset(other *Complex128Set) bool {
	return other.IsSubset(&s)
}

// Union returns a new union set of s and other.
func (s Complex128Set) Union(other *Complex128Set) *Complex128Set {
	result := s.Copy()
	other.Visit(func(value complex128) bool {
		result.Add(value)
		return true
	})
	return result
}

// Slice returns a slice of complex128s copied from the set contents.
func (s Complex128Set) Slice() []complex128 {
	result := make([]complex128, 0, len(s.m))
	for value := range s.m {
		result = append(result, value)
	}
	return result
}

// Len returns the size of the set.
func (s Complex128Set) Len() int {
	return len(s.m)
}

// IsEmpty return true is set is empty, false otherwise.
func (s Complex128Set) IsEmpty() bool {
	return len(s.m) == 0
}
