// Code generated by "gends"; DO NOT EDIT.

package set // import "kkn.fi/set"

// Float32 implements a set data structure that holds float32s.
type Float32 struct {
	m map[float32]struct{}
}

// NewFloat32 creates a set of float32s initialized with given values.
func NewFloat32(values ...float32) *Float32 {
	s := &Float32{}
	s.m = make(map[float32]struct{})
	s.Add(values...)
	return s
}

// Add adds given values to the set.
func (s *Float32) Add(values ...float32) {
	if len(values) == 0 {
		return
	}
	for _, value := range values {
		s.m[value] = valueExists
	}
}

// Contains returns true if set holds all values and false otherwise.
func (s *Float32) Contains(values ...float32) bool {
	if len(values) == 0 {
		return false
	}
	for _, value := range values {
		if _, has := s.m[value]; !has {
			return false
		}
	}
	return true
}

// Remove removes given values from the set.
func (s *Float32) Remove(values ...float32) {
	if len(values) == 0 {
		return
	}
	for _, value := range values {
		delete(s.m, value)
	}
}

// Clear removes all values from the set.
func (s *Float32) Clear() {
	s.m = make(map[float32]struct{})
}

// Visit iterates through the set and visits all values with function f.
// Iteration will stop if function f returns false.
// Visit will return false when set is visited partially.
func (s *Float32) Visit(f func(value float32) bool) bool {
	for v := range s.m {
		if !f(v) {
			return false
		}
	}
	return true
}

// Copy returns a copy of the set.
func (s *Float32) Copy() *Float32 {
	return NewFloat32(s.Slice()...)
}

// Equals returns true if both sets are equal, but false otherwise.
func (s *Float32) Equals(other *Float32) bool {
	if s.Len() != other.Len() {
		return false
	}
	e := true
	other.Visit(func(value float32) bool {
		_, e = s.m[value]
		return e
	})
	return e
}

// IsSubset returns true if given set is a subset of s.
func (s *Float32) IsSubset(other *Float32) bool {
	result := true
	other.Visit(func(value float32) bool {
		_, result = s.m[value]
		return result
	})
	return result
}

// IsSuperset returns true if given set is a superset of s.
func (s *Float32) IsSuperset(other *Float32) bool {
	return other.IsSubset(s)
}

// Union returns a new union set of s and other.
func (s *Float32) Union(other *Float32) *Float32 {
	result := s.Copy()
	other.Visit(func(value float32) bool {
		result.Add(value)
		return true
	})
	return result
}

// Slice returns a slice of float32s copied from the set contents.
func (s *Float32) Slice() []float32 {
	result := make([]float32, 0, len(s.m))
	for value := range s.m {
		result = append(result, value)
	}
	return result
}

// Len returns the size of the set.
func (s *Float32) Len() int {
	return len(s.m)
}

// IsEmpty return true is set is empty, false otherwise.
func (s *Float32) IsEmpty() bool {
	return len(s.m) == 0
}
