// Code generated by "gends"; DO NOT EDIT.

package set // import "kkn.fi/set"

// Float64Set implements a set data structure that holds float64s.
type Float64Set struct {
	m map[float64]struct{}
}

// NewFloat64 creates a set of float64s initialized with given values.
func NewFloat64(values ...float64) *Float64Set {
	s := &Float64Set{}
	s.m = make(map[float64]struct{})
	s.Add(values...)
	return s
}

// Add adds given values to the set.
func (s *Float64Set) Add(values ...float64) {
	if len(values) == 0 {
		return
	}
	for _, value := range values {
		s.m[value] = valueExists
	}
}

// Contains returns true if set holds all values and false otherwise.
func (s *Float64Set) Contains(values ...float64) bool {
	if len(values) == 0 {
		return false
	}
	for _, value := range values {
		if _, has := s.m[value]; !has {
			return false
		}
	}
	return true
}

// Remove removes given values from the set.
func (s *Float64Set) Remove(values ...float64) {
	if len(values) == 0 {
		return
	}
	for _, value := range values {
		delete(s.m, value)
	}
}

// Clear removes all values from the set.
func (s *Float64Set) Clear() {
	s.m = make(map[float64]struct{})
}

// Visit iterates through the set and visits all values with function f.
// Iteration will stop if function f returns false.
// Visit will return false when set is visited partially.
func (s *Float64Set) Visit(f func(value float64) bool) bool {
	for v := range s.m {
		if !f(v) {
			return false
		}
	}
	return true
}

// Copy returns a copy of the set.
func (s *Float64Set) Copy() *Float64Set {
	return NewFloat64(s.Slice()...)
}

// Equals returns true if both sets are equal, but false otherwise.
func (s *Float64Set) Equals(other *Float64Set) bool {
	if s.Len() != other.Len() {
		return false
	}
	e := true
	other.Visit(func(value float64) bool {
		_, e = s.m[value]
		return e
	})
	return e
}

// IsSubset returns true if given set is a subset of s.
func (s *Float64Set) IsSubset(other *Float64Set) bool {
	result := true
	other.Visit(func(value float64) bool {
		_, result = s.m[value]
		return result
	})
	return result
}

// IsSuperset returns true if given set is a superset of s.
func (s *Float64Set) IsSuperset(other *Float64Set) bool {
	return other.IsSubset(s)
}

// Union returns a new union set of s and other.
func (s *Float64Set) Union(other *Float64Set) *Float64Set {
	result := s.Copy()
	other.Visit(func(value float64) bool {
		result.Add(value)
		return true
	})
	return result
}

// Slice returns a slice of float64s copied from the set contents.
func (s *Float64Set) Slice() []float64 {
	result := make([]float64, 0, len(s.m))
	for value := range s.m {
		result = append(result, value)
	}
	return result
}

// Len returns the size of the set.
func (s *Float64Set) Len() int {
	return len(s.m)
}

// IsEmpty return true is set is empty, false otherwise.
func (s *Float64Set) IsEmpty() bool {
	return len(s.m) == 0
}
