// Code generated by "gends"; DO NOT EDIT.

package set // import "kkn.fi/set"

// Int implements a set data structure that holds ints.
type Int struct {
	m map[int]struct{}
}

// NewInt creates a set of ints initialized with given values.
func NewInt(values ...int) *Int {
	s := &Int{}
	s.m = make(map[int]struct{})
	s.Add(values...)
	return s
}

// Add adds given values to the set.
func (s *Int) Add(values ...int) {
	if len(values) == 0 {
		return
	}
	for _, value := range values {
		s.m[value] = valueExists
	}
}

// Contains returns true if set holds all values and false otherwise.
func (s *Int) Contains(values ...int) bool {
	if len(values) == 0 {
		return false
	}
	for _, value := range values {
		if _, has := s.m[value]; !has {
			return false
		}
	}
	return true
}

// Remove removes given values from the set.
func (s *Int) Remove(values ...int) {
	if len(values) == 0 {
		return
	}
	for _, value := range values {
		delete(s.m, value)
	}
}

// Clear removes all values from the set.
func (s *Int) Clear() {
	s.m = make(map[int]struct{})
}

// Visit iterates through the set and visits all values with function f.
// Iteration will stop if function f returns false.
// Visit will return false when set is visited partially.
func (s *Int) Visit(f func(value int) bool) bool {
	for v := range s.m {
		if !f(v) {
			return false
		}
	}
	return true
}

// Copy returns a copy of the set.
func (s *Int) Copy() *Int {
	return NewInt(s.Slice()...)
}

// Equals returns true if both sets are equal, but false otherwise.
func (s *Int) Equals(other *Int) bool {
	if s.Len() != other.Len() {
		return false
	}
	e := true
	other.Visit(func(value int) bool {
		_, e = s.m[value]
		return e
	})
	return e
}

// IsSubset returns true if given set is a subset of s.
func (s *Int) IsSubset(other *Int) bool {
	result := true
	other.Visit(func(value int) bool {
		_, result = s.m[value]
		return result
	})
	return result
}

// IsSuperset returns true if given set is a superset of s.
func (s *Int) IsSuperset(other *Int) bool {
	return other.IsSubset(s)
}

// Union returns a new union set of s and other.
func (s *Int) Union(other *Int) *Int {
	result := s.Copy()
	other.Visit(func(value int) bool {
		result.Add(value)
		return true
	})
	return result
}

// Slice returns a slice of ints copied from the set contents.
func (s *Int) Slice() []int {
	result := make([]int, 0, len(s.m))
	for value := range s.m {
		result = append(result, value)
	}
	return result
}

// Len returns the size of the set.
func (s *Int) Len() int {
	return len(s.m)
}

// IsEmpty return true is set is empty, false otherwise.
func (s *Int) IsEmpty() bool {
	return len(s.m) == 0
}
