// Code generated by "gends"; DO NOT EDIT.

package set // import "kkn.fi/set"

// Int16Set implements a set data structure that holds int16s.
type Int16Set struct {
	m map[int16]struct{}
}

// NewInt16 creates a set of int16s initialized with given values.
func NewInt16(values ...int16) *Int16Set {
	s := &Int16Set{}
	s.m = make(map[int16]struct{})
	s.Add(values...)
	return s
}

// Add adds given values to the set.
func (s *Int16Set) Add(values ...int16) {
	if len(values) == 0 {
		return
	}
	for _, value := range values {
		s.m[value] = valueExists
	}
}

// Contains returns true if set holds all values and false otherwise.
func (s *Int16Set) Contains(values ...int16) bool {
	if len(values) == 0 {
		return false
	}
	for _, value := range values {
		if _, has := s.m[value]; !has {
			return false
		}
	}
	return true
}

// Remove removes given values from the set.
func (s *Int16Set) Remove(values ...int16) {
	if len(values) == 0 {
		return
	}
	for _, value := range values {
		delete(s.m, value)
	}
}

// Clear removes all values from the set.
func (s *Int16Set) Clear() {
	s.m = make(map[int16]struct{})
}

// Visit iterates through the set and visits all values with function f.
// Iteration will stop if function f returns false.
// Visit will return false when set is visited partially.
func (s *Int16Set) Visit(f func(value int16) bool) bool {
	for v := range s.m {
		if !f(v) {
			return false
		}
	}
	return true
}

// Copy returns a copy of the set.
func (s *Int16Set) Copy() *Int16Set {
	return NewInt16(s.Slice()...)
}

// Equals returns true if both sets are equal, but false otherwise.
func (s *Int16Set) Equals(other *Int16Set) bool {
	if s.Len() != other.Len() {
		return false
	}
	e := true
	other.Visit(func(value int16) bool {
		_, e = s.m[value]
		return e
	})
	return e
}

// IsSubset returns true if given set is a subset of s.
func (s *Int16Set) IsSubset(other *Int16Set) bool {
	result := true
	other.Visit(func(value int16) bool {
		_, result = s.m[value]
		return result
	})
	return result
}

// IsSuperset returns true if given set is a superset of s.
func (s *Int16Set) IsSuperset(other *Int16Set) bool {
	return other.IsSubset(s)
}

// Union returns a new union set of s and other.
func (s *Int16Set) Union(other *Int16Set) *Int16Set {
	result := s.Copy()
	other.Visit(func(value int16) bool {
		result.Add(value)
		return true
	})
	return result
}

// Slice returns a slice of int16s copied from the set contents.
func (s *Int16Set) Slice() []int16 {
	result := make([]int16, 0, len(s.m))
	for value := range s.m {
		result = append(result, value)
	}
	return result
}

// Len returns the size of the set.
func (s *Int16Set) Len() int {
	return len(s.m)
}

// IsEmpty return true is set is empty, false otherwise.
func (s *Int16Set) IsEmpty() bool {
	return len(s.m) == 0
}
