// Code generated by "gends"; DO NOT EDIT.

package set // import "kkn.fi/set"

// Int32 implements a set data structure that holds int32s.
type Int32 struct {
	m map[int32]struct{}
}

// NewInt32 creates a set of int32s initialized with given values.
func NewInt32(values ...int32) *Int32 {
	s := &Int32{}
	s.m = make(map[int32]struct{})
	s.Add(values...)
	return s
}

// Add adds given values to the set.
func (s *Int32) Add(values ...int32) {
	if len(values) == 0 {
		return
	}
	for _, value := range values {
		s.m[value] = valueExists
	}
}

// Contains returns true if set holds all values and false otherwise.
func (s *Int32) Contains(values ...int32) bool {
	if len(values) == 0 {
		return false
	}
	for _, value := range values {
		if _, has := s.m[value]; !has {
			return false
		}
	}
	return true
}

// Remove removes given values from the set.
func (s *Int32) Remove(values ...int32) {
	if len(values) == 0 {
		return
	}
	for _, value := range values {
		delete(s.m, value)
	}
}

// Clear removes all values from the set.
func (s *Int32) Clear() {
	s.m = make(map[int32]struct{})
}

// Visit iterates through the set and visits all values with function f.
// Iteration will stop if function f returns false.
// Visit will return false when set is visited partially.
func (s *Int32) Visit(f func(value int32) bool) bool {
	for v := range s.m {
		if !f(v) {
			return false
		}
	}
	return true
}

// Copy returns a copy of the set.
func (s *Int32) Copy() *Int32 {
	return NewInt32(s.Slice()...)
}

// Equals returns true if both sets are equal, but false otherwise.
func (s *Int32) Equals(other *Int32) bool {
	if s.Len() != other.Len() {
		return false
	}
	e := true
	other.Visit(func(value int32) bool {
		_, e = s.m[value]
		return e
	})
	return e
}

// IsSubset returns true if given set is a subset of s.
func (s *Int32) IsSubset(other *Int32) bool {
	result := true
	other.Visit(func(value int32) bool {
		_, result = s.m[value]
		return result
	})
	return result
}

// IsSuperset returns true if given set is a superset of s.
func (s *Int32) IsSuperset(other *Int32) bool {
	return other.IsSubset(s)
}

// Union returns a new union set of s and other.
func (s *Int32) Union(other *Int32) *Int32 {
	result := s.Copy()
	other.Visit(func(value int32) bool {
		result.Add(value)
		return true
	})
	return result
}

// Slice returns a slice of int32s copied from the set contents.
func (s *Int32) Slice() []int32 {
	result := make([]int32, 0, len(s.m))
	for value := range s.m {
		result = append(result, value)
	}
	return result
}

// Len returns the size of the set.
func (s *Int32) Len() int {
	return len(s.m)
}

// IsEmpty return true is set is empty, false otherwise.
func (s *Int32) IsEmpty() bool {
	return len(s.m) == 0
}
