// Code generated by "gends"; DO NOT EDIT.

package set // import "kkn.fi/set"

// Int8 implements a set data structure that holds int8s.
type Int8 struct {
	m map[int8]struct{}
}

// NewInt8 creates a set of int8s initialized with given values.
func NewInt8(values ...int8) *Int8 {
	s := &Int8{}
	s.m = make(map[int8]struct{})
	s.Add(values...)
	return s
}

// Add adds given values to the set.
func (s *Int8) Add(values ...int8) {
	if len(values) == 0 {
		return
	}
	for _, value := range values {
		s.m[value] = valueExists
	}
}

// Contains returns true if set holds all values and false otherwise.
func (s *Int8) Contains(values ...int8) bool {
	if len(values) == 0 {
		return false
	}
	for _, value := range values {
		if _, has := s.m[value]; !has {
			return false
		}
	}
	return true
}

// Remove removes given values from the set.
func (s *Int8) Remove(values ...int8) {
	if len(values) == 0 {
		return
	}
	for _, value := range values {
		delete(s.m, value)
	}
}

// Clear removes all values from the set.
func (s *Int8) Clear() {
	s.m = make(map[int8]struct{})
}

// Visit iterates through the set and visits all values with function f.
// Iteration will stop if function f returns false.
// Visit will return false when set is visited partially.
func (s *Int8) Visit(f func(value int8) bool) bool {
	for v := range s.m {
		if !f(v) {
			return false
		}
	}
	return true
}

// Copy returns a copy of the set.
func (s *Int8) Copy() *Int8 {
	return NewInt8(s.Slice()...)
}

// Equals returns true if both sets are equal, but false otherwise.
func (s *Int8) Equals(other *Int8) bool {
	if s.Len() != other.Len() {
		return false
	}
	e := true
	other.Visit(func(value int8) bool {
		_, e = s.m[value]
		return e
	})
	return e
}

// IsSubset returns true if given set is a subset of s.
func (s *Int8) IsSubset(other *Int8) bool {
	result := true
	other.Visit(func(value int8) bool {
		_, result = s.m[value]
		return result
	})
	return result
}

// IsSuperset returns true if given set is a superset of s.
func (s *Int8) IsSuperset(other *Int8) bool {
	return other.IsSubset(s)
}

// Union returns a new union set of s and other.
func (s *Int8) Union(other *Int8) *Int8 {
	result := s.Copy()
	other.Visit(func(value int8) bool {
		result.Add(value)
		return true
	})
	return result
}

// Slice returns a slice of int8s copied from the set contents.
func (s *Int8) Slice() []int8 {
	result := make([]int8, 0, len(s.m))
	for value := range s.m {
		result = append(result, value)
	}
	return result
}

// Len returns the size of the set.
func (s *Int8) Len() int {
	return len(s.m)
}

// IsEmpty return true is set is empty, false otherwise.
func (s *Int8) IsEmpty() bool {
	return len(s.m) == 0
}
