// Code generated by "gends"; DO NOT EDIT.

package set // import "kkn.fi/set"

// RuneSet implements a set data structure that holds runes.
type RuneSet struct {
	m map[rune]struct{}
}

// NewRune creates a set of runes initialized with given values.
func NewRune(values ...rune) *RuneSet {
	s := &RuneSet{}
	s.m = make(map[rune]struct{})
	s.Add(values...)
	return s
}

// Add adds given values to the set.
func (s *RuneSet) Add(values ...rune) {
	if len(values) == 0 {
		return
	}
	for _, value := range values {
		s.m[value] = valueExists
	}
}

// Contains returns true if set holds all values and false otherwise.
func (s *RuneSet) Contains(values ...rune) bool {
	if len(values) == 0 {
		return false
	}
	for _, value := range values {
		if _, has := s.m[value]; !has {
			return false
		}
	}
	return true
}

// Remove removes given values from the set.
func (s *RuneSet) Remove(values ...rune) {
	if len(values) == 0 {
		return
	}
	for _, value := range values {
		delete(s.m, value)
	}
}

// Clear removes all values from the set.
func (s *RuneSet) Clear() {
	s.m = make(map[rune]struct{})
}

// Visit iterates through the set and visits all values with function f.
// Iteration will stop if function f returns false.
// Visit will return false when set is visited partially.
func (s *RuneSet) Visit(f func(value rune) bool) bool {
	for v := range s.m {
		if !f(v) {
			return false
		}
	}
	return true
}

// Copy returns a copy of the set.
func (s *RuneSet) Copy() *RuneSet {
	return NewRune(s.Slice()...)
}

// Equals returns true if both sets are equal, but false otherwise.
func (s *RuneSet) Equals(other *RuneSet) bool {
	if s.Len() != other.Len() {
		return false
	}
	e := true
	other.Visit(func(value rune) bool {
		_, e = s.m[value]
		return e
	})
	return e
}

// IsSubset returns true if given set is a subset of s.
func (s *RuneSet) IsSubset(other *RuneSet) bool {
	result := true
	other.Visit(func(value rune) bool {
		_, result = s.m[value]
		return result
	})
	return result
}

// IsSuperset returns true if given set is a superset of s.
func (s *RuneSet) IsSuperset(other *RuneSet) bool {
	return other.IsSubset(s)
}

// Union returns a new union set of s and other.
func (s *RuneSet) Union(other *RuneSet) *RuneSet {
	result := s.Copy()
	other.Visit(func(value rune) bool {
		result.Add(value)
		return true
	})
	return result
}

// Slice returns a slice of runes copied from the set contents.
func (s *RuneSet) Slice() []rune {
	result := make([]rune, 0, len(s.m))
	for value := range s.m {
		result = append(result, value)
	}
	return result
}

// Len returns the size of the set.
func (s *RuneSet) Len() int {
	return len(s.m)
}

// IsEmpty return true is set is empty, false otherwise.
func (s *RuneSet) IsEmpty() bool {
	return len(s.m) == 0
}
