// Code generated by "gends"; DO NOT EDIT.

package set // import "kkn.fi/set"

// Uint implements a set data structure that holds uints.
type Uint struct {
	m map[uint]struct{}
}

// NewUint creates a set of uints initialized with given values.
func NewUint(values ...uint) *Uint {
	s := &Uint{}
	s.m = make(map[uint]struct{})
	s.Add(values...)
	return s
}

// Add adds given values to the set.
func (s *Uint) Add(values ...uint) {
	if len(values) == 0 {
		return
	}
	for _, value := range values {
		s.m[value] = valueExists
	}
}

// Contains returns true if set holds all values and false otherwise.
func (s *Uint) Contains(values ...uint) bool {
	if len(values) == 0 {
		return false
	}
	for _, value := range values {
		if _, has := s.m[value]; !has {
			return false
		}
	}
	return true
}

// Remove removes given values from the set.
func (s *Uint) Remove(values ...uint) {
	if len(values) == 0 {
		return
	}
	for _, value := range values {
		delete(s.m, value)
	}
}

// Clear removes all values from the set.
func (s *Uint) Clear() {
	s.m = make(map[uint]struct{})
}

// Visit iterates through the set and visits all values with function f.
// Iteration will stop if function f returns false.
// Visit will return false when set is visited partially.
func (s *Uint) Visit(f func(value uint) bool) bool {
	for v := range s.m {
		if !f(v) {
			return false
		}
	}
	return true
}

// Copy returns a copy of the set.
func (s *Uint) Copy() *Uint {
	return NewUint(s.Slice()...)
}

// Equals returns true if both sets are equal, but false otherwise.
func (s *Uint) Equals(other *Uint) bool {
	if s.Len() != other.Len() {
		return false
	}
	e := true
	other.Visit(func(value uint) bool {
		_, e = s.m[value]
		return e
	})
	return e
}

// IsSubset returns true if given set is a subset of s.
func (s *Uint) IsSubset(other *Uint) bool {
	result := true
	other.Visit(func(value uint) bool {
		_, result = s.m[value]
		return result
	})
	return result
}

// IsSuperset returns true if given set is a superset of s.
func (s *Uint) IsSuperset(other *Uint) bool {
	return other.IsSubset(s)
}

// Union returns a new union set of s and other.
func (s *Uint) Union(other *Uint) *Uint {
	result := s.Copy()
	other.Visit(func(value uint) bool {
		result.Add(value)
		return true
	})
	return result
}

// Slice returns a slice of uints copied from the set contents.
func (s *Uint) Slice() []uint {
	result := make([]uint, 0, len(s.m))
	for value := range s.m {
		result = append(result, value)
	}
	return result
}

// Len returns the size of the set.
func (s *Uint) Len() int {
	return len(s.m)
}

// IsEmpty return true is set is empty, false otherwise.
func (s *Uint) IsEmpty() bool {
	return len(s.m) == 0
}
