// Code generated by "gends"; DO NOT EDIT.

package set // import "kkn.fi/set"

// Uint16 implements a set data structure that holds uint16s.
type Uint16 struct {
	m map[uint16]struct{}
}

// NewUint16 creates a set of uint16s initialized with given values.
func NewUint16(values ...uint16) *Uint16 {
	s := &Uint16{}
	s.m = make(map[uint16]struct{})
	s.Add(values...)
	return s
}

// Add adds given values to the set.
func (s *Uint16) Add(values ...uint16) {
	if len(values) == 0 {
		return
	}
	for _, value := range values {
		s.m[value] = valueExists
	}
}

// Contains returns true if set holds all values and false otherwise.
func (s *Uint16) Contains(values ...uint16) bool {
	if len(values) == 0 {
		return false
	}
	for _, value := range values {
		if _, has := s.m[value]; !has {
			return false
		}
	}
	return true
}

// Remove removes given values from the set.
func (s *Uint16) Remove(values ...uint16) {
	if len(values) == 0 {
		return
	}
	for _, value := range values {
		delete(s.m, value)
	}
}

// Clear removes all values from the set.
func (s *Uint16) Clear() {
	s.m = make(map[uint16]struct{})
}

// Visit iterates through the set and visits all values with function f.
// Iteration will stop if function f returns false.
// Visit will return false when set is visited partially.
func (s *Uint16) Visit(f func(value uint16) bool) bool {
	for v := range s.m {
		if !f(v) {
			return false
		}
	}
	return true
}

// Copy returns a copy of the set.
func (s *Uint16) Copy() *Uint16 {
	return NewUint16(s.Slice()...)
}

// Equals returns true if both sets are equal, but false otherwise.
func (s *Uint16) Equals(other *Uint16) bool {
	if s.Len() != other.Len() {
		return false
	}
	e := true
	other.Visit(func(value uint16) bool {
		_, e = s.m[value]
		return e
	})
	return e
}

// IsSubset returns true if given set is a subset of s.
func (s *Uint16) IsSubset(other *Uint16) bool {
	result := true
	other.Visit(func(value uint16) bool {
		_, result = s.m[value]
		return result
	})
	return result
}

// IsSuperset returns true if given set is a superset of s.
func (s *Uint16) IsSuperset(other *Uint16) bool {
	return other.IsSubset(s)
}

// Union returns a new union set of s and other.
func (s *Uint16) Union(other *Uint16) *Uint16 {
	result := s.Copy()
	other.Visit(func(value uint16) bool {
		result.Add(value)
		return true
	})
	return result
}

// Slice returns a slice of uint16s copied from the set contents.
func (s *Uint16) Slice() []uint16 {
	result := make([]uint16, 0, len(s.m))
	for value := range s.m {
		result = append(result, value)
	}
	return result
}

// Len returns the size of the set.
func (s *Uint16) Len() int {
	return len(s.m)
}

// IsEmpty return true is set is empty, false otherwise.
func (s *Uint16) IsEmpty() bool {
	return len(s.m) == 0
}
