// Code generated by "gends"; DO NOT EDIT.

package set // import "kkn.fi/set"

// Uint64Set implements a set data structure that holds uint64s.
type Uint64Set struct {
	m map[uint64]struct{}
}

// NewUint64 creates a set of uint64s initialized with given values.
func NewUint64(values ...uint64) *Uint64Set {
	s := &Uint64Set{}
	s.m = make(map[uint64]struct{})
	s.Add(values...)
	return s
}

// Add adds given values to the set.
func (s *Uint64Set) Add(values ...uint64) {
	if len(values) == 0 {
		return
	}
	for _, value := range values {
		s.m[value] = valueExists
	}
}

// Contains returns true if set holds all values and false otherwise.
func (s Uint64Set) Contains(values ...uint64) bool {
	if len(values) == 0 {
		return false
	}
	for _, value := range values {
		if _, has := s.m[value]; !has {
			return false
		}
	}
	return true
}

// Remove removes given values from the set.
func (s *Uint64Set) Remove(values ...uint64) {
	if len(values) == 0 {
		return
	}
	for _, value := range values {
		delete(s.m, value)
	}
}

// Clear removes all values from the set.
func (s *Uint64Set) Clear() {
	s.m = make(map[uint64]struct{})
}

// Visit iterates through the set and visits all values with function f.
// Iteration will stop if function f returns false.
// Visit will return false when set is visited partially.
func (s Uint64Set) Visit(f func(value uint64) bool) bool {
	for v := range s.m {
		if !f(v) {
			return false
		}
	}
	return true
}

// Copy returns a copy of the set.
func (s Uint64Set) Copy() *Uint64Set {
	return NewUint64(s.Slice()...)
}

// Equals returns true if both sets are equal, but false otherwise.
func (s Uint64Set) Equals(other *Uint64Set) bool {
	if s.Len() != other.Len() {
		return false
	}
	e := true
	other.Visit(func(value uint64) bool {
		_, e = s.m[value]
		return e
	})
	return e
}

// IsSubset returns true if given set is a subset of s.
func (s Uint64Set) IsSubset(other *Uint64Set) bool {
	result := true
	other.Visit(func(value uint64) bool {
		_, result = s.m[value]
		return result
	})
	return result
}

// IsSuperset returns true if given set is a superset of s.
func (s Uint64Set) IsSuperset(other *Uint64Set) bool {
	return other.IsSubset(&s)
}

// Union returns a new union set of s and other.
func (s Uint64Set) Union(other *Uint64Set) *Uint64Set {
	result := s.Copy()
	other.Visit(func(value uint64) bool {
		result.Add(value)
		return true
	})
	return result
}

// Slice returns a slice of uint64s copied from the set contents.
func (s Uint64Set) Slice() []uint64 {
	result := make([]uint64, 0, len(s.m))
	for value := range s.m {
		result = append(result, value)
	}
	return result
}

// Len returns the size of the set.
func (s Uint64Set) Len() int {
	return len(s.m)
}

// IsEmpty return true is set is empty, false otherwise.
func (s Uint64Set) IsEmpty() bool {
	return len(s.m) == 0
}
