// Code generated by "gends"; DO NOT EDIT.

package set // import "kkn.fi/set"

// Uint8Set implements a set data structure that holds uint8s.
type Uint8Set struct {
	m map[uint8]struct{}
}

// NewUint8 creates a set of uint8s initialized with given values.
func NewUint8(values ...uint8) *Uint8Set {
	s := &Uint8Set{}
	s.m = make(map[uint8]struct{})
	s.Add(values...)
	return s
}

// Add adds given values to the set.
func (s *Uint8Set) Add(values ...uint8) {
	if len(values) == 0 {
		return
	}
	for _, value := range values {
		s.m[value] = valueExists
	}
}

// Contains returns true if set holds all values and false otherwise.
func (s *Uint8Set) Contains(values ...uint8) bool {
	if len(values) == 0 {
		return false
	}
	for _, value := range values {
		if _, has := s.m[value]; !has {
			return false
		}
	}
	return true
}

// Remove removes given values from the set.
func (s *Uint8Set) Remove(values ...uint8) {
	if len(values) == 0 {
		return
	}
	for _, value := range values {
		delete(s.m, value)
	}
}

// Clear removes all values from the set.
func (s *Uint8Set) Clear() {
	s.m = make(map[uint8]struct{})
}

// Visit iterates through the set and visits all values with function f.
// Iteration will stop if function f returns false.
// Visit will return false when set is visited partially.
func (s *Uint8Set) Visit(f func(value uint8) bool) bool {
	for v := range s.m {
		if !f(v) {
			return false
		}
	}
	return true
}

// Copy returns a copy of the set.
func (s *Uint8Set) Copy() *Uint8Set {
	return NewUint8(s.Slice()...)
}

// Equals returns true if both sets are equal, but false otherwise.
func (s *Uint8Set) Equals(other *Uint8Set) bool {
	if s.Len() != other.Len() {
		return false
	}
	e := true
	other.Visit(func(value uint8) bool {
		_, e = s.m[value]
		return e
	})
	return e
}

// IsSubset returns true if given set is a subset of s.
func (s *Uint8Set) IsSubset(other *Uint8Set) bool {
	result := true
	other.Visit(func(value uint8) bool {
		_, result = s.m[value]
		return result
	})
	return result
}

// IsSuperset returns true if given set is a superset of s.
func (s *Uint8Set) IsSuperset(other *Uint8Set) bool {
	return other.IsSubset(s)
}

// Union returns a new union set of s and other.
func (s *Uint8Set) Union(other *Uint8Set) *Uint8Set {
	result := s.Copy()
	other.Visit(func(value uint8) bool {
		result.Add(value)
		return true
	})
	return result
}

// Slice returns a slice of uint8s copied from the set contents.
func (s *Uint8Set) Slice() []uint8 {
	result := make([]uint8, 0, len(s.m))
	for value := range s.m {
		result = append(result, value)
	}
	return result
}

// Len returns the size of the set.
func (s *Uint8Set) Len() int {
	return len(s.m)
}

// IsEmpty return true is set is empty, false otherwise.
func (s *Uint8Set) IsEmpty() bool {
	return len(s.m) == 0
}
